Update FastlaneV2.yml

diff --git a/.github/workflows/FastlaneV2.yml b/.github/workflows/FastlaneV2.yml
--- a/.github/workflows/FastlaneV2.yml
+++ b/.github/workflows/FastlaneV2.yml
@@ -157,6 +157,87 @@ jobs:
       - name: Clean DerivedData
         run: rm -rf ~/Library/Developer/Xcode/DerivedData
 
+      - name: Corrigir função install_framework no script do CocoaPods
+        run: |
+          cat <<'EOF' > ios/App/Pods/Target\ Support\ Files/Pods-App/Pods-App-frameworks.sh
+          #!/bin/sh
+          set -e
+          set -u
+          set -o pipefail
+      
+          function on_error {
+            echo "$(realpath -mq "${0}"):$1: error: Unexpected failure"
+          }
+          trap 'on_error $LINENO' ERR
+      
+          if [ -z ${FRAMEWORKS_FOLDER_PATH+x} ]; then
+            exit 0
+          fi
+      
+          echo "mkdir -p ${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
+          mkdir -p "${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
+      
+          COCOAPODS_PARALLEL_CODE_SIGN="${COCOAPODS_PARALLEL_CODE_SIGN:-false}"
+          SWIFT_STDLIB_PATH="${TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}"
+          RSYNC_PROTECT_TMP_FILES=(--filter "P .*.??????")
+      
+          install_framework()
+          {
+            echo "📦 Embedding framework: $1"
+      
+            if [ -r "${BUILT_PRODUCTS_DIR}/$1" ]; then
+              local source="${BUILT_PRODUCTS_DIR}/$1"
+            elif [ -r "${BUILT_PRODUCTS_DIR}/$(basename "$1")" ]; then
+              local source="${BUILT_PRODUCTS_DIR}/$(basename "$1")"
+            elif [ -r "$1" ]; then
+              local source="$1"
+            else
+              echo "❌ Framework $1 not found"
+              return
+            fi
+      
+            local destination="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
+            echo "📁 Copying from $source to $destination"
+      
+            rsync --delete -av "${RSYNC_PROTECT_TMP_FILES[@]}" \
+              --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" \
+              --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" \
+              "$source" "$destination"
+      
+            local basename
+            basename="$(basename -s .framework "$1")"
+            binary="$destination/$basename.framework/$basename"
+      
+            if [ -r "$binary" ]; then
+              code_sign_if_enabled "$binary"
+            fi
+          }
+      
+          code_sign_if_enabled() {
+            if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" -a "${CODE_SIGNING_REQUIRED:-}" != "NO" -a "${CODE_SIGNING_ALLOWED}" != "NO" ]; then
+              echo "🔏 Code Signing $1 with Identity ${EXPANDED_CODE_SIGN_IDENTITY_NAME}"
+              local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements '$1'"
+              if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
+                code_sign_cmd="$code_sign_cmd &"
+              fi
+              echo "$code_sign_cmd"
+              eval "$code_sign_cmd"
+            fi
+          }
+      
+          if [[ "$CONFIGURATION" == "Debug" || "$CONFIGURATION" == "Release" ]]; then
+            install_framework "${BUILT_PRODUCTS_DIR}/Capacitor/Capacitor.framework"
+            install_framework "${BUILT_PRODUCTS_DIR}/CapacitorCordova/Cordova.framework"
+            install_framework "${BUILT_PRODUCTS_DIR}/CapacitorLocalNotifications/CapacitorLocalNotifications.framework"
+            install_framework "${BUILT_PRODUCTS_DIR}/CapacitorPushNotifications/CapacitorPushNotifications.framework"
+            install_framework "${BUILT_PRODUCTS_DIR}/CordovaPlugins/CordovaPlugins.framework"
+          fi
+      
+          if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
+            wait
+          fi
+          EOF
+
       - name: Run Fastlane
         run: |
           cd ios/App
